version : '3'

services :
  db :
    container_name: my-db
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=porpor
      - POSTGRES_PASSWORD=1102003440132por
    image: postgres:14.4
    restart: unless-stopped

  pgadmin :
    container_name : pg-admin
    ports:
      - 4433:443
      - 8080:80
    environment :
      - PGADMIN_DEFAULT_EMAIL=picklock007x@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1102003440132por
    image : dpage/pgadmin4:latest
    restart : unless-stopped

  strapi :
    container_name : my-app2
    ports:
      - 1337:1337
    environment :
      - name=value
      - DATABASE_CLIENT=postgres
      - DATABASE_PORT=54321
      - DATABASE_NAME=postgres
      - DATABASE_HOST=192.168.56.1
      - DATABASE_USERNAME=porpor
      - DATABASE_PASSWORD=1102003440132por
      - DATABASE_SSL=false
    image: 'naskio/strapi:latest'  
    restart: 'unless-stopped' 